set(BUILD_TESTING OFF)
set(NONET ON)
add_definitions(-DUINT8_MAX=255 -D_PPCINLINE_SOCKET_H -DEXEC_IO_H -D_PPCINLINE_EXEC_H -Dfseeko=fseek)
if(NOT USE_SDL1)
  set(DEVILUTIONX_SYSTEM_LIBPNG ON)
  set(DEVILUTIONX_SYSTEM_SDL_IMAGE ON)
  set(SDL2_LIBRARY /gg/usr/lib/libSDL2.a)
  set(SDL2_INCLUDE_DIR /gg/usr/include/SDL2)
  set(SDL2_image_INCLUDE_DIR /gg/usr/include/SDL2)
  link_libraries(SDL2)
  include_directories(/gg/usr/include/SDL2)
endif()
